name: Documentation

on:
  push:
    branches: [ "**" ]
    paths:
      - "docs/"
  pull_request:
    branches: [ "main" ]
    paths:
      - "docs/"

jobs:

  documentation: 
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2.0.0
      - name: build
        run: echo "hey"        
