name: Identity Server

on:
  push:
    branches: [ "**" ]
    paths: [ "src-identity_server/" ]
    
  pull_request:
    branches: [ "main" ]
    paths: [ "src-identity_server/" ]

jobs:
     
  identity-server:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: build
        run: echo "hey"
        
